---
HOSTS:
  debian9-64-1:
    pe_dir:
    pe_ver:
    pe_upgrade_dir:
    pe_upgrade_ver:
    hypervisor: docker
    docker_cmd:
    - "/sbin/init"
    image: debian:9
    platform: debian-9-amd64
    packaging_platform: debian-9-amd64
    docker_image_commands:
    - cp /bin/true /sbin/agetty
    - rm -f /usr/sbin/policy-rc.d
    - apt-get update && apt-get install -y cron locales-all net-tools wget systemd-sysv
      gnupg
    - mkdir /etc/systemd/system/corosync.service.d
    - echo "[Service]\nType=simple" > /etc/systemd/system/corosync.service.d/10-simple-type.conf
    roles:
    - agent
CONFIG:
  nfs_server: none
  consoleport: 443
